services:
    frontend-reloader:
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: frontend
        container_name: bpc-frontend-reloader
        command: npm run watch-sass
        volumes:
            - .:/code/:Z
            # NOTE: We do not want node_modules on the host machine, so we
            # create an additional volume for it. It is important this anonymous
            # volume comes after the above bind to work.
            - /code/nodejs/node_modules/
    application:
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: os2borgerpc
        image: bpc
        pull_policy: never
        container_name: bpc-application
        env_file:
            - path: ./dev-environment/bpc.env
            - path: ./dev-environment/overrides.env
              required: false
        # --reload reloads on changes to python files only - not CSS, HTML etc.
        # A reload should not be needed for HTML, CSS etc. as long as they aren't cached
        command:
            sh -c "./manage.py initialize_database /code/dev-environment/fixtures &&
                   ./manage.py compilemessages &&
                   gunicorn --reload
                   --reload-extra-file /code/admin_site/locale/da/LC_MESSAGES/django.mo
                   --reload-extra-file /code/admin_site/locale/da/LC_MESSAGES/djangojs.mo
                   --reload-extra-file /code/admin_site/locale/sv/LC_MESSAGES/django.mo
                   --reload-extra-file /code/admin_site/locale/sv/LC_MESSAGES/djangojs.mo
                   --timeout 0 --config /code/docker/gunicorn-settings.py os2borgerpc_admin.wsgi"
        volumes:
            - .:/code/
        depends_on:
            - db
        ports:
            - 9999:9999
        stdin_open: true
        tty: true
        privileged: true
    cron:
        image: bpc
        pull_policy: never
        container_name: bpc-cron
        env_file:
            - path: ./dev-environment/bpc.env
        volumes:
            - .:/code/
        command: ["supercronic", "/crontab"]
        entrypoint: []
        depends_on:
            - application
    db:
        image: postgres:18
        container_name: bpc-db
        restart: always
        env_file:
            - path: ./dev-environment/bpc.env
        volumes:
            - postgres-data:/var/lib/postgresql

volumes:
    postgres-data:
