# Generated by Django 4.2.11 on 2024-07-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0086_remove_featurepermission_sites_remove_site_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageversion",
            name="published",
            field=models.BooleanField(default=True, verbose_name="published (visible)"),
        ),
        migrations.AlterField(
            model_name="imageversion",
            name="release_notes",
            field=models.TextField(max_length=6000),
        ),
    ]
