# Generated by Django 4.2.11 on 2024-07-09 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0087_imageversion_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageversion",
            name="image_upload",
            field=models.FileField(
                blank=True, default="#", null=True, upload_to="images"
            ),
        ),
        migrations.AlterField(
            model_name="imageversion",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="system.product",
                verbose_name="product",
            ),
        ),
    ]
