# Generated by Django 4.2.15 on 2024-09-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0088_alter_imageversion_image_upload_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wakeweekplan",
            name="sleep_state",
            field=models.CharField(
                choices=[
                    ("STANDBY", "Standby (S1)"),
                    ("FREEZE", "Freeze"),
                    ("MEM", "Mem (S3)"),
                    ("OFF", "Off (S5)"),
                ],
                default="OFF",
                max_length=10,
                verbose_name="sleep state",
            ),
        ),
    ]
