# Generated by Django 4.2.15 on 2024-10-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0090_pc_product_product_config_name_product_short_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configurationentry",
            options={
                "ordering": ["key"],
                "verbose_name_plural": "configuration entries",
            },
        ),
    ]
