# Generated by Django 4.2.15 on 2024-10-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0092_alter_wakeweekplan_sleep_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configurationentry",
            options={
                "ordering": ["read_only", "key"],
                "verbose_name_plural": "configuration entries",
            },
        ),
        migrations.AddField(
            model_name="configurationentry",
            name="read_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pc",
            name="name",
            field=models.CharField(
                help_text="Valid characters are a-z, A-Z, 0-9 and hyphen (-). The length must be 1-63 characters",
                max_length=255,
                verbose_name="name",
            ),
        ),
    ]
