# Generated by Django 4.2.15 on 2024-10-29 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0093_alter_configurationentry_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuration",
            name="name",
        ),
    ]
