# Generated by Django 4.2.15 on 2024-10-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0094_remove_configuration_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wakeweekplan",
            name="sleep_state",
            field=models.CharField(
                choices=[
                    ("FREEZE", "Freeze (S2)"),
                    ("MEM", "Mem (S3)"),
                    ("OFF", "Off (S5)"),
                ],
                default="OFF",
                max_length=10,
                verbose_name="sleep state",
            ),
        ),
    ]
