# Generated by Django 4.2.15 on 2025-01-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0095_alter_wakeweekplan_sleep_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="dashboard_hidden",
            field=models.BooleanField(
                default=False, verbose_name="hidden on dashboard"
            ),
        ),
    ]
