# Generated by Django 4.2.15 on 2025-01-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0096_job_dashboard_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="using_sso",
            field=models.BooleanField(
                default=False, verbose_name="Enable to require SSO"
            ),
        ),
    ]
