# Generated by Django 4.2.19 on 2025-03-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0097_customer_using_sso"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="site_prefix",
            field=models.CharField(
                max_length=40, null=True, verbose_name="site prefix"
            ),
        ),
    ]
