# Generated by Django 4.2.19 on 2025-03-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0097_customer_using_sso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pc",
            name="name",
            field=models.CharField(
                help_text="Valid characters are a-z, A-Z, 0-9 and hyphen (-). The length must be 1-40 characters",
                max_length=40,
                verbose_name="name",
            ),
        ),
    ]
