# Generated by Django 4.2.19 on 2025-07-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0099_alter_pc_name_alter_site_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="script",
            name="maintained_by_magenta",
        ),
    ]
