# Generated by Django 4.2.19 on 2025-11-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0100_remove_script_maintained_by_magenta"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="created"
            ),
        ),
    ]
