# Generated by Django 4.2.19 on 2025-11-10 11:12

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0101_customer_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pc",
            name="name",
            field=models.CharField(
                help_text="Valid characters are a-z, A-Z, 0-9 and hyphen (-). The length must be 1-40 characters",
                max_length=40,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9]+$"),
                        "Enter a valid name consisting of letters, numbers or hyphens.",
                    )
                ],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="uid",
            field=models.CharField(
                max_length=40,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-z0-9]+$"),
                        "Enter a valid “UID” consisting of lowercase letters, numbers or hyphens.",
                    )
                ],
                verbose_name="UID",
            ),
        ),
    ]
