# Generated by Django 4.2.19 on 2025-11-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0102_alter_pc_name_alter_site_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginlog",
            name="pc_uid",
            field=models.CharField(
                default="N/A", max_length=255, verbose_name="PC UID"
            ),
        ),
    ]
