# Generated by Django 4.2.19 on 2025-11-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0103_loginlog_pc_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="script",
            name="description",
            field=models.TextField(max_length=8190, verbose_name="description"),
        ),
    ]
