# Generated by Django 4.2.27 on 2025-12-16 11:37

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0105_alter_pc_name_alter_site_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pc",
            name="name",
            field=models.CharField(
                help_text="Valid characters are (English) letters, numbers and hyphens. The length must be 1-40 characters.<br/>Note: If you change this, the computer's hostname will be updated, becoming a lowercased version of the new name.",
                max_length=40,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9]+$"),
                        "Enter a valid name consisting of (English) letters, numbers or hyphens.",
                    )
                ],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="uid",
            field=models.CharField(
                max_length=40,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-z0-9]+$"),
                        "Enter a valid “UID” consisting of lowercase (English) letters, numbers or hyphens.",
                    )
                ],
                verbose_name="UID",
            ),
        ),
    ]
