# Generated by Django 4.2.27 on 2026-01-08 13:02

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0106_alter_pc_name_alter_site_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pc",
            name="name",
            field=models.CharField(
                help_text="Valid characters are (English) letters, numbers and hyphens. The length must be 1-40 characters.<br/>Note: If you change this, the computer's hostname will be updated, becoming a lowercased version of the new name.",
                max_length=40,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[a-zA-Z0-9][-a-zA-Z0-9]*$"),
                        "Enter a valid name consisting of (English) letters, numbers or hyphens.",
                    )
                ],
                verbose_name="name",
            ),
        ),
    ]
