# Generated by Django 4.2.15 on 2024-10-29 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0108_alter_pc_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pc",
            name="configuration",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="system.configuration"
            ),
        ),
        migrations.AlterField(
            model_name="pcgroup",
            name="configuration",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="system.configuration"
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="configuration",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="system.configuration"
            ),
        ),
    ]
