# Generated by Django 4.2.28 on 2026-03-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0110_fileparameter"),
    ]

    operations = [
        migrations.CreateModel(
            name="PCsOverviewV",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("site_id", models.IntegerField()),
                ("product_id", models.IntegerField()),
                ("configuration_id", models.IntegerField()),
                ("configurationentry_id", models.IntegerField()),
                ("created", models.DateTimeField()),
                ("description", models.CharField()),
                ("is_activated", models.BooleanField(verbose_name="activated")),
                ("last_seen", models.DateTimeField(verbose_name="last seen")),
                ("location", models.CharField()),
                ("mac", models.CharField(verbose_name="MAC")),
                ("name", models.CharField()),
                ("online", models.BooleanField()),
                ("os_release", models.CharField(verbose_name="OS release")),
                (
                    "product_short_name",
                    models.CharField(verbose_name="product short name"),
                ),
                ("uid", models.CharField(verbose_name="UID")),
            ],
            options={
                "db_table": "system_pc_overview_v",
                "managed": False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE VIEW system_pc_overview_v AS
            SELECT
            "system_pc"."id" AS "id",
            "system_pc"."site_id",
            "system_pc"."product_id",
            "system_pc"."configuration_id",
            "system_configurationentry"."id" AS "configurationentry_id",
            "system_pc"."created",
            "system_pc"."description",
            "system_pc"."is_activated",
            "system_pc"."last_seen",
            "system_pc"."location",
            "system_pc"."mac",
            "system_pc"."name",
            CASE WHEN NOT("system_pc"."is_activated") THEN false
            WHEN ("system_pc"."last_seen" > NOW() - INTERVAL '5 minutes') THEN true
            ELSE false END AS online,
            "system_configurationentry"."value" AS os_release,
            "system_product"."short_name" AS "product_short_name",
            "system_pc"."uid"
            FROM "system_pc"
            INNER JOIN "system_configuration"
            ON ("system_pc"."configuration_id" = "system_configuration"."id")
            LEFT OUTER JOIN "system_product"
            ON ("system_pc"."product_id" = "system_product"."id")
            LEFT OUTER JOIN "system_configurationentry"
            ON ("system_configurationentry"."owner_configuration_id" = "system_configuration"."id"
            AND "system_configurationentry"."key" = '_os_release')
            ;
            """,
            "DROP VIEW system_pc_overview_v;",
        ),
    ]
