# Generated by Django 5.2.13 on 2026-05-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0112_alter_pc_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="is_test",
        ),
        migrations.AddField(
            model_name="customer",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Onboarding"),
                    (1, "Aboard"),
                    (2, "Offboarding"),
                    (3, "Offboard"),
                ],
                default=0,
            ),
        ),
    ]
