# Generated by Django 5.2.13 on 2026-05-11 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0113_remove_customer_is_test_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.script'),
        ),
    ]
