# Generated by Django 5.2.13 on 2026-06-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0114_alter_batch_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='paid_for_access_until',
            field=models.DateField(blank=True, null=True, verbose_name='Version access until'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='using_sso',
            field=models.BooleanField(default=False, verbose_name='Require SSO'),
        ),
    ]
