# Generated by Django 5.2.13 on 2026-06-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0115_alter_customer_paid_for_access_until_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='paid_for_access_until',
            new_name='version_access_until',
        ),
    ]
