# Generated by Django 5.2.13 on 2026-08-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0116_rename_paid_for_access_until_customer_version_access_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='client_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Client key'),
        ),
    ]
