# Generated by Django 4.2.28 on 2026-04-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("changelog", "0002_remove_changelog_author_remove_changelog_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changelog",
            name="description",
            field=models.TextField(
                blank=True, max_length=240, verbose_name="description"
            ),
        ),
    ]
